### ISSUE TITLE
Domain'in süresi dolmuş

### ISSUE THREAD

**Issue by ulgens** [pyistanbul/itspython#1]
Domain'in süresi dolduğu için site erişim dışı.

Expected Results: Yenileyiverin hacılar.

**Comment by berkerpeksag** [comment]
@fatiherikli domain sende miydi?

**Comment by berkerpeksag** [comment]
Domaini yeniledik, şu an site açık. Haber verdiğin için teşekkürler Ülgen.

**Comment by cenkalti** [comment]
@fatiherikli domain sende sanirim?

**Comment by berkerpeksag** [comment]
Domain Erikli'de ama geçen sene ben yenilemiştim. Şu an bilgileri bulamadım. Ping @fatiherikli.

**Comment by berkerpeksag** [comment]
<3 <3 <3
