### ISSUE TITLE
Domain gene dolmuş :(

### ISSUE THREAD

**Issue by ulgens** [pyistanbul/itspython#3]
Yeniliyor muyuz, yoksa ölüme terk mi?

**Comment by ardatan** [comment]
Bunu ciddi ciddi github’a atmissiniz ya helal olsun 😂

**Comment by ulgens** [comment]
@ardatan Çünkü projeyle ilgili, ve daha önce iki sefer buradan çözüldü.

**Comment by ardatan** [comment]
anladim :) ben de kullaniyorum bu web sitesini. yanlis anlamayin icinde tek html olan bir proje oldugunu gorunce biraz komik geliyor insana. iyi calismalar, kolay gelsin

**Comment by berkerpeksag** [comment]
@fatiherikli üç ay kalmış sürenin dolmasına. Yenileyelim mi yoksa artık helvasını yiyelim mi?

**Comment by ulgens** [comment]
@berkerpeksag Domain son boşa düştüğünde ben aldım, düzenli yenilemeyi düşünyorum. Eşe dosta yolluyorum güzel oluyor :)

**Comment by berkerpeksag** [comment]
@ulgens süper! Çok teşekkürler :) O zaman bu issue'yu kapatıyorum şimdilik.
